Repository bromagosa/snapCloud, pull requests merged in 2018-09, with the labels that each got.

#123 Use noreply@snap.berkeley.edu as the sending email
  config.lua
Labels: ops

#130 Log more information to nginx logs
  config.lua
  nginx.conf
Labels: ops

#121 Use extensions subdomain for http-only Snap!.
  cors.lua
  nginx.conf.d/extensions.conf
  nginx.conf.d/http-only.conf
  nginx.conf.d/ssl-production.conf
Labels: enhancement, ops

#126 Encode username and token URL parameters
  api.lua
  snap-cloud-beta-0.rockspec
  validation.lua
Labels: bug

#131 Reset Error logging back to 'warn'
  config.lua
Labels: ops

#142 set store path when running tests
  config.lua
Labels: enhancement

#124 Redirect unknown domains to the default_server
  nginx.conf.d/http-only.conf
Labels: enhancement
